<?php
/**
 * Redis Management Module
 * 
 * @category   Steverobbins
 * @package    Steverobbins_Redismanager
 * @author     Steve Robbins <steven.j.robbins@gmail.com>
 * @copyright  Copyright (c) 2014 Steve Robbins (https://github.com/steverobbins)
 * @license    http://creativecommons.org/licenses/by/3.0/deed.en_US Creative Commons Attribution 3.0 Unported License
 */
/**
 * @var Steverobbins_Redismanager_Block_Adminhtml_Manager $this
 */
$_services = $this->getSortedServices();
?>
<script>
    var charts = [];
    function getRandomColor() {
        var letters = '0123456789ABCDEF'.split('');
        var color = '#';
        for (var i = 0; i < 6; i++ ) {
            color += letters[Math.floor(Math.random() * 16)];
        }
        return color;
    }
</script>
<div class="redismanager manager">
    <button id="flushAll" title="<?php echo $this->__('Flush All') ?>" type="button" class="scalable delete right" onclick="setLocation('<?php echo $this->getUrl('*/*/flushAll') ?> ')"><span><span><span><?php echo $this->__('Flush All') ?></span></span></span></button>
    <div class="content-header">
        <h3><?php echo $this->__('Servers') ?></h3>
    </div>
    <div class="servers">
    <?php $_i = 0 ?>
    <?php foreach ($_services as $_host => $_service): ?>
        <?php $_info = $_service['info'] ?>
        <div class="server">
            <h4><?php echo $_host ?></h4>
            <div class="chart">
                <h4><?php echo $this->__('Keys') ?></h4>
                <canvas id="chart-<?php echo $_i ?>" width="400" height="400"></canvas>
            </div>
            <script>
                charts[<?php echo $_i ?>] = [];
                <?php foreach ($_service['services'] as $_id => $_db): ?>
                var color = getRandomColor();
                charts[<?php echo $_i ?>].push({
                    value: <?php echo $_db['keys'] ?>,
                    label: '<?php echo $_db['name'] ?>',
                    color: color,
                    highlight: color
                });
                <?php endforeach ?>
            </script>
            <table>
                <tr>
                    <th>Version</th>
                    <td><?php echo $_info['redis_version'] ?></td>
                </tr>
                <tr>
                    <th>Uptime</th>
                    <td><?php printf(
                        '%s day(s) %02d:%02d:%02d',
                        floor($_info['uptime_in_seconds'] / 86400),
                        floor($_info['uptime_in_seconds'] / 3600) % 24,
                        floor($_info['uptime_in_seconds'] / 60) % 60,
                        floor($_info['uptime_in_seconds'] % 60)
                    ) ?></td>
                </tr>
                <tr>
                    <th>Connected Clients</th>
                    <td><?php echo $_info['connected_clients'] ?></td>
                </tr>
                <?php if ($_info['connected_slaves']): ?>
                <tr>
                    <th>Connected Slaves</th>
                    <td><?php echo $_info['connected_slaves'] ?></td>
                </tr>
                <?php endif ?>
                <tr>
                    <th>Used Memory</th>
                    <td><?php echo $_info['used_memory_human'] ?></td>
                </tr>
                <tr>
                    <th>Peak Used Memory</th>
                    <td><?php echo $_info['used_memory_peak_human'] ?></td>
                </tr>
                <tr>
                    <th>Expired Keys</th>
                    <td><?php echo $_info['expired_keys'] ?></td>
                </tr>
                <tr>
                    <th>Evicted Keys</th>
                    <td><?php echo $_info['evicted_keys'] ?></td>
                </tr>
                <tr>
                    <th>Keyspace Hits</th>
                    <td><?php echo $_info['keyspace_hits'] ?></td>
                </tr>
                <tr>
                    <th>Keyspace Misses</th>
                    <td><?php echo $_info['keyspace_misses'] ?></td>
                </tr>
            </table>
        </div>
        <?php $_i++ ?>
    <?php endforeach ?>
    </div>
    <?php if (count($_services)): ?>
    <?php $_coreHelper = $this->helper('core') ?>
    <?php $_date = Mage::getSingleton('core/date') ?>
    <div class="content-header">
        <h3><?php echo $this->__('Delete Keys') ?></h3>
    </div>
    <form id="flushByKey" action="<?php echo $this->getUrl('*/*/flushByKey') ?>" method="post">
        <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
        <fieldset>
            <div>
                <label for="redisKeys"><?php echo $this->__('Keys (complete or partial, case sensative, one per line):') ?></label>
            </div>
            <div class="redisKeySamples">
                <p><?php echo $this->__('Examples:') ?></p>
                <ul>
                    <li><a id="redisKeySampleCategory" href="#" data-keys="CATEGORY"><?php echo $this->__('Categories') ?></a></li>
                    <li><a id="redisKeySampleProduct" href="#" data-keys="PRODUCT"><?php echo $this->__('Products') ?></a></li>
                    <li><a id="redisKeySampleProduct" href="#" data-keys="BLOCK,CMS,LAYOUT,THEME"><?php echo $this->__('Design & Layout') ?></a></li>
                    <li><a id="redisKeySampleProduct" href="#" data-keys="LOCALE,Locale,TRANSLATE"><?php echo $this->__('Locale') ?></a></li>
                </ul>
                <p style="clear:both"><em><?php echo $this->__('Keys can also be deleted by using <a href="%s">Cache Management</a>.', $this->getUrl('*/cache')) ?></em></p>
            </div>
            <div>
                <textarea id="redisKeys" name="redisKeys"></textarea>
            </div>
            <div>
                <button><?php echo $this->__('Delete Keys') ?></button>
            </div>
        </fieldset>
    </form>
    <?php endif ?>
</div>
<script>
// <![CDATA[
for (var i = 0; i < charts.length; i++) {
    new Chart(document.getElementById('chart-' + i).getContext('2d'))
        .Pie(charts[i], {
            animationEasing: false
        });
}
/*
var redisForm = $('redisServices');
function redisCheckAll() {
    redisForm.getElements('checkbox').each(function(box) {
        box.checked = true; 
    });
}
function redisCheckNone() {
    redisForm.getElements('checkbox').each(function(box) {
        box.checked = false; 
    });
}
function redisCheckRow(tr) {
    var box = tr.getElementsByTagName('input');
    for (var i = 0; i < box.length; i++) {
        if (box[i].type === 'checkbox') {
            box[i].checked = !box[i].checked;
        }
    }   
}*/

$$('.redisKeySamples a').each(function(elem) {
    $(elem).on('click', 'a', function() {
        $('redisKeys').value = $(elem).readAttribute('data-keys').replace(/,/g, '\n');
    });
});
// ]]>
</script>