<?php
/**
 * Redis Management Module
 * 
 * @category   Steverobbins
 * @package    Steverobbins_Redismanager
 * @author     Steve Robbins <steven.j.robbins@gmail.com>
 * @copyright  Copyright (c) 2014 Steve Robbins (https://github.com/steverobbins)
 * @license    http://creativecommons.org/licenses/by/3.0/deed.en_US Creative Commons Attribution 3.0 Unported License
 */
/**
 * @var Steverobbins_Redismanager_Block_Adminhtml_Manager $this
 */
?>
<script>
// <![CDATA[
var redisForm;
// ]]>
</script>
<div class="redismanager refresher">
    <button id="redismanager-refresh-now" type="button" class="scalable"><span><span><?php echo $this->__('Refresh') ?></span></span></button>
    <p class="auto"><?php echo $this->__('Refresh every %s seconds', '<input type="text" id="redismanager-refresh-interval" value="0" />') ?> <input type="submit" id="redismanager-refresh-set" value="<?php echo $this->__('Set') ?>" /></p>
</div>
<div class="redismanager manager">
    <div id="redismanager-grid">
        <?php echo $this->getChildHtml('redismanager.grid') ?>
    </div>
    <?php if (count($this->getSortedServices())): ?>
    <?php $_coreHelper = $this->helper('core') ?>
    <?php $_date = Mage::getSingleton('core/date') ?>
    <div class="content-header">
        <h3><?php echo $this->__('Delete Keys') ?></h3>
    </div>
    <form id="flushByKey" action="<?php echo $this->getUrl('*/*/flushByKey') ?>" method="post">
        <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
        <fieldset>
            <div>
                <label for="redisKeys"><?php echo $this->__('Keys (complete or partial, case sensative, one per line):') ?></label>
            </div>
            <div class="redisKeySamples">
                <p><?php echo $this->__('Examples:') ?></p>
                <ul>
                    <li><a id="redisKeySampleCategory" href="#" data-keys="CATEGORY"><?php echo $this->__('Categories') ?></a></li>
                    <li><a id="redisKeySampleProduct" href="#" data-keys="PRODUCT"><?php echo $this->__('Products') ?></a></li>
                    <li><a id="redisKeySampleProduct" href="#" data-keys="BLOCK,CMS,LAYOUT,THEME"><?php echo $this->__('Design & Layout') ?></a></li>
                    <li><a id="redisKeySampleProduct" href="#" data-keys="LOCALE,Locale,TRANSLATE"><?php echo $this->__('Locale') ?></a></li>
                </ul>
                <p style="clear:both"><em><?php echo $this->__('Keys can also be deleted by using <a href="%s">Cache Management</a>.', $this->getUrl('*/cache')) ?></em></p>
            </div>
            <div>
                <textarea id="redisKeys" name="redisKeys"></textarea>
            </div>
            <div>
                <button><?php echo $this->__('Delete Keys') ?></button>
            </div>
        </fieldset>
    </form>
    <script>
    // <![CDATA[
    $$('.redisKeySamples a').each(function(elem) {
        $(elem).on('click', 'a', function() {
            $('redisKeys').value = $(elem).readAttribute('data-keys').replace(/,/g, '\n');
        });
    });
    // ]]>
    </script>
    <?php endif ?>
</div>
<script>
// <![CDATA[
var redismanagerRefresh;
$('redismanager-refresh-set').on('click', function() {
    var interval = parseInt($('redismanager-refresh-interval').value);
    clearInterval(redismanagerRefresh);
    if (interval) {
        redisRefreshGrid();
        redismanagerRefresh = setInterval(function() {
            redisRefreshGrid();
        }, interval * 1000);
    }
    return false;
});
$('redismanager-refresh-now').on('click', function() {
    redisRefreshGrid();
    return false;
});
function redisRefreshGrid() {
    new Ajax.Updater('redismanager-grid', '<?php echo $this->getUrl("*/*/grid") ?>', {evalScripts: true});
}
function redisCheckAll() {
    redisForm.getElements('checkbox').each(function(box) {
        box.checked = true; 
    });
}
function redisCheckNone() {
    redisForm.getElements('checkbox').each(function(box) {
        box.checked = false; 
    });
}
function redisCheckRow(tr) {
    var box = tr.getElementsByTagName('input');
    for (var i = 0; i < box.length; i++) {
        if (box[i].type === 'checkbox') {
            box[i].checked = !box[i].checked;
        }
    }   
}
// ]]>
</script>
